### ISSUE TITLE
Animals dataset

### ISSUE THREAD

**Issue by zekaouinoureddine** [oke-aditya/image_similarity#8]
Hi @oke-aditya, 
Thanks for your great work and thanks for making it available for the community. The [blog post](https://medium.com/pytorch/image-similarity-search-in-pytorch-1a744cf3469) is just fantastic. Indeed, I opened this issue to ask for the **animal dataset** you used. I reproduced the code and I need the dataset to run it, please if it is possible to share it with us. Thanks again!

**Comment by oke-aditya** [comment]
Hi! This request has come often. 

I will look for local copy of dataset and try to upload it over kaggle as public dataset. Also share a link to Jupyter notebook. 

Hopefully this all is possible. Since the dataset was created locally and should I have a copy of it on my laptop. 

Might take 1-2 weeks but will update here. 

Thanks @zekaouinoureddine

**Comment by oke-aditya** [comment]
Here is the link, sorry for the delay.
https://www.kaggle.com/datasets/okeaditya/animals-data

**Comment by zekaouinoureddine** [comment]
Well received, thanks you so much! 🤙🏼
